export enum AojSubmissionStatus {
	STATE_COMPILEERROR = 0,
	STATE_WRONGANSWER = 1,
	STATE_TIMELIMIT = 2,
	STATE_MEMORYLIMIT = 3,
	STATE_ACCEPTED = 4,
	STATE_WAITING = 5,
	STATE_OUTPUTLIMIT = 6,
	STATE_RUNTIMEERROR = 7,
	STATE_PRESENTATIONERROR = 8,
	STATE_RUNNING = 9,
}
